
version: "3.9"
services:
  saints-api:
    image: ${ACR_REGISTRY}/saints-api:${IMAGE_TAG}
    build:
      context: ./api/SaintsApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  angular-client:
    image: ${ACR_REGISTRY}/saints-ui:${IMAGE_TAG}
    build:
      context: ./ui/saints-ui
      dockerfile: Dockerfile