#Multistage Dockerfile (STAGE 1: build, STAGE 2: run)

# 1: build
FROM node:22 AS build
WORKDIR /app

# 2: copy and install dependencies
COPY package*.json ./
RUN npm ci

#3: copy the rest of the source code
COPY . .

# 4: build the app for prod
RUN npm run build -- --configuration production

# 5 serve
FROM nginx:alpine

# 6: copy
COPY --from=build /app/dist/saints-ui/browser /usr/share/nginx/html

# 7: expose
EXPOSE 80

# start nginx
CMD ["nginx", "-g", "daemon off;"]

