#Multistage Dockerfile (STAGE 1: build, STAGE 2: run)

FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy package.json and package-lock.json first (for caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Expose port Angular serves on
EXPOSE 4200

# Start Angular
CMD ["ng", "serve", "--host", "0.0.0.0"]
